name: 'Pulumi runner'
description: 'Pulumi runner (non official)'
inputs:
  stack:
    description: 'Pulumi Stack to working with'
    required: true
  args:
    description: 'pulumi args to run with'
    required: true
  mode:
    description: 'Supported values: pr & up'
    required: false
  root:
    description: "Pulumi's root path"
    required: false
  comment-on-pr:
    description: "Leave a comment for PRs"
    required: false
  github-token:
    description: "Github Token"
    required: false
  yarn:
    description: "Set to true to force yarn"
    required: false
  monorepo:
    description: "Set to anything if using a monorepo repository (e.g. lerna)"
    required: false
branding:
  icon: 'gift'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'
